language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: mobileera-2019
  token:
    secure: tM3rg3bo7vPqKOk8n2LaS8BLpr2IMZBA3aZE5/BPSMGz6hiU06z0RIr2XVajaS/LwNypNncXXa3c2k5r9K+2X/sDYAQlh0/j1jARx4yBvWd8Kjo49EshHNpCjizM6U1cOb8kXGBXYksYpH3cSmRhof2iipLmKAXD/j2y7+MqFfJ0+yG+Akk31cIU8TkwJrWmMQBE5UqU22OtZhmfn0znPvnZk5xOdlaL8J4O5DudX9q1KW5F6NkKnVFtRaYnhRr88Mk4ozjmR/RUILbupedr9+PPg4TQSW32OI1Y3BrFv9xwRNtkwBgn1zHDRyjMCOGBFhcj/TbB8JC/flEZJliasL5kWh6wM1lz+3rqZ103neeIC03tF3QDZT1xFMcDLc2VhOEQYIsz4RqnPvopqYnu5mRPOpd6Q9XVECJ7KGGkkwETLIQaxfcCFK6/oGuJTocZKrUfOxQo5gunxzc5SNeTx2jB1Ri9f4By6eBf84wMPVunFJKZcJtoZKsJMTxN2aa8/fwXBhtao6p+hKlWpH7nFFdDcxW9d5THPXmwWZcMMeCn+vrs6yYGDqcQvmAEvF/hG1AhJrvc6YP0EvfWQ1DKP+5JYiysWXyUUeHVvoULBAI9/EHIlNNVYmUKTR0JCGlWhPYLNeondGiUu6lE9P043jtDRFAJD02IrWlBK+/CaUE=
