language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: mobileera-2019
  token:
    secure: rH3zh3H88RFCWkOH4EXTLkZ2x6uMDhLuJFXQzQb/sHJxP/TOirk8ne/Lg1NxEDvG1obTNSCliSjfSsCrl58Mf6opF3w8tn4cD+05ugvvtLvWpEDImBT/voRkoSTyOwKC63RycF1gm501eKIv9wBIwBhAy2Th/AxBZE/+kJMM+HtXVZnh0vJhI5tBburVkODadD8fIhv0yKtzOY4CtcJhEx015maC6+9aECemuD0geS3/qz/sSo+hheMhNP0SKgMc4oMX61R/9R7hjmbYvyf4vJzqc79eOvcPfvVbptckmnCvn7REL2elihLoPVH2I7F6ylDi44EIgnK7KdAjlF73Hb9QiCbYV73DkKqZYJKsmIi4rJLWqQ9BCa/S2+yKcHAtzxZA+aVNSzCJ3xxiV5v5e6J8s0Xr8M1va7vgpeAEogyMy3UTIlzz0k+qXwzAGBD3S1YC7WKEUShD7EkcYgHvHloUC48izsCcfrmvtxWCSGlPSwPcaz4v/gtScRISnhoUjpkEaVlBk/Qc+01VqAqeIT6U2QdYVALYY1z+oLtuDeHZDnvORKgbg3+0ZOy/tEFOrl2fJkjqMdN4M4Do+Lyi8+KGKmLNvyisxCoenGSWCNBxyeg1gUjTbFGCpYHQTToBOBzeBd10Befrrf4m+NmWXWaP6e9ihr9kxFKZqxWFiM0=
- provider: firebase
  skip_cleanup: true